

GET http://api.icndb.com/jokes/random?limitTo=[nerdy]&firstName=Sahitya&lastName=Subramanian

###
GET http://localhost:8080/api/tutorials

###
POST http://localhost:8080/api/tutorials
Content-Type: application/json

{
  "title" : "spring-boot",
  "description": "book about spring-boot",
  "published" : "true"
}

###
GET http://localhost:8080/api/tutorials/published

